services:
  - type: web
    name: nightscout
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: MONGO_CONNECTION
        value: mongodb+srv://WendieDB:fuqre0-bivdix-jabcUt@cluster0.pr9ysdv.mongodb.net/ nightscout?retryWrites=true&w=majority&appName=Cluster0
      - key: API_SECRET
        value: W3ndi3Rav3n!
      - key: DISPLAY_UNITS
        value: mmol
      - key: ENABLE
        value: careportal basal iob cob
      - key: TZ
        value: Europe/Amsterdam
